export const TABLE_DATA_GET_DATA = 'TABLE_DATA_GET_DATA';
export const TABLE_DATA_GET_DATA_SUCCESS = 'TABLE_DATA_GET_DATA_SUCCESS';
export const TABLE_DATA_GET_DATA_ERROR = 'TABLE_DATA_GET_DATA_ERROR';

export const TABLE_DATA_SET_LIMIT = 'TABLE_DATA_SET_LIMIT';
export const TABLE_DATA_SET_PAGE = 'TABLE_DATA_SET_PAGE';