export const TABLE_DATA_GET_DATA = 'GET_DATA';
export const TABLE_DATA_GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const TABLE_DATA_GET_DATA_ERROR = 'GET_DATA_ERROR';

export const TABLE_DATA_SET_LIMIT = 'SET_LIMIT';
export const TABLE_DATA_SET_PAGE = 'SET_PAGE';